version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3010:3000"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:5000

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5010:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/appointment_scheduler  # Update this line
    depends_on:
      - db  # Ensure backend waits for db to be ready

  db:
    image: postgres:latest  # Use the latest PostgreSQL image
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appointment_scheduler
    ports:
      - "5432-5435:5432"
