version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3010:3000"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:5000

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5010:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///app.db 